version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/:/app

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8888:80"
    depends_on:
      - app
    volumes:
      - ./src/:/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
      - MYSQL_ROOT_PASSWORD=testpassword
      - TZ=Japan
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./docker/db/mysql/data:/var/lib/mysql
